# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c14e8a16a7ba4e11a4b95f624cc8989a2535fcf8f2746306a266419e3b3826b812385788e14d250d6fbba084896d5450e5af16b844afef4b2ef16d3a9afd656

test:
  secret_key_base: 1c441df1d90650d097648995ce10073e55aacb34d252c45aa11e9e7d29c769c7bc5d3876b72a74627d78c7d207f0da43b908bb2645b2adb172ec3bd899076959

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
